version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8001:8000"  # Farklı port (mevcut container çakışmasın)
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
    environment:
      - ENV=production

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: devops
      POSTGRES_USER: irem
      POSTGRES_PASSWORD: devops123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
